### ISSUE TITLE
Generate local database with docker

### ISSUE THREAD

**Issue by ksreyr** [Indie-Creator-Community/side-project-starter-kit#4]
### What problem does your feature request solve?

with this feature won't be needed the handle of supabase in order to create a database for the project 

### Describe the solution you'd like

With docker compose is possible to run a local db and use it for development

### Describe alternatives you've considered

none, docker is the perfect

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serudda** [comment]
DONE
