### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by Zyruks** [Indie-Creator-Community/side-project-starter-kit#6]
### What problem does your feature request solve?

Beginners may face difficulty in running the project without prior knowledge of the project dependencies and setup.

### Describe the solution you'd like

Add Docker support to the project, which will simplify the setup process and make it easier to run the project.

### Describe alternatives you've considered

None, as Docker is the most suitable and widely used solution for simplifying the setup and configuration of projects.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serudda** [comment]
DONE
